/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.rasporedutakmica;

import form.utakmica.TableModelUtakmica;
import form.utakmica.UtakmicaForm;
import controller.ClientController;
import domen.Klub;
import domen.RasporedUtakmica;
import domen.StatistikaKluba;
import domen.Utakmica;
import form.FormEnum;
import java.awt.Frame;
import java.net.SocketException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

public class NewRasporedUtakmicaForm extends javax.swing.JDialog {

    private RasporedUtakmica rasporedUtakmica;
    private TableModelUtakmica tableModelUtakmica;

    public NewRasporedUtakmicaForm(java.awt.Frame parent, boolean modal, RasporedUtakmica rasporedUtakmica) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.rasporedUtakmica = rasporedUtakmica;
        this.tableModelUtakmica = new TableModelUtakmica(new LinkedList<>());
        tblUtakmice.setModel(tableModelUtakmica);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUtakmice = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnObrisiUtakmicu = new javax.swing.JButton();
        btnDodajUtakmicu = new javax.swing.JToggleButton();
        txtSezona = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setText("Sezona");

        tblUtakmice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUtakmice);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnObrisiUtakmicu.setText("Obrisi utakmicu");
        btnObrisiUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUtakmicuActionPerformed(evt);
            }
        });

        btnDodajUtakmicu.setText("Dodaj utakmicu");
        btnDodajUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUtakmicuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSezona))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajUtakmicu)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiUtakmicu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSezona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiUtakmicu)
                    .addComponent(btnDodajUtakmicu))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String sezona = txtSezona.getText();
            if(sezona.isEmpty()){
                throw new Exception("Niste uneli naziv sezone");
            }
            
            List<Utakmica> utakmice = tableModelUtakmica.getList();
            
            if(utakmice.isEmpty()){
                throw new Exception("Morate uneti barem jednu utakmicu");
            }
            
            rasporedUtakmica.setSezona(sezona);
            rasporedUtakmica.setUtakmice(utakmice);
            rasporedUtakmica.setAdministrator(ClientController.getInstance().getUlogovani());
            ClientController.getInstance().saveRasporedUtakmica(rasporedUtakmica);
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste sacuvali raspored utakmica");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnDodajUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUtakmicuActionPerformed
        Utakmica utakmica = new Utakmica();
        utakmica.setRaspored(rasporedUtakmica);
        new UtakmicaForm((Frame) this.getParent(), rootPaneCheckingEnabled, utakmica, FormEnum.NOVI, tableModelUtakmica).setVisible(true);
    }//GEN-LAST:event_btnDodajUtakmicuActionPerformed

    private void btnObrisiUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUtakmicuActionPerformed
        int row = tblUtakmice.getSelectedRow();
        if (row > -1) {
            tableModelUtakmica.removeUtakmica(row);
        }
    }//GEN-LAST:event_btnObrisiUtakmicuActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        tableModelUtakmica.refreshTable();
    }//GEN-LAST:event_formWindowGainedFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JToggleButton btnDodajUtakmicu;
    private javax.swing.JButton btnObrisiUtakmicu;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUtakmice;
    private javax.swing.JTextField txtSezona;
    // End of variables declaration//GEN-END:variables

}
