/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.utakmica;

import controller.ClientController;
import domen.Klub;
import domen.Utakmica;
import form.FormEnum;
import java.net.SocketException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class UtakmicaForm extends javax.swing.JDialog {

    /**
     * Creates new form EditUtakmicaForm
     */
    
    private Utakmica utakmica;
    private FormEnum formEnum;
    private TableModelUtakmica tableModelUtakmica;
    
    public UtakmicaForm(java.awt.Frame parent, boolean modal, Utakmica utakmica, FormEnum formEnum, TableModelUtakmica tableModelUtakmica) {
        super(parent, modal);
        initComponents();
        this.utakmica = utakmica;
        this.formEnum = formEnum;
        this.tableModelUtakmica = tableModelUtakmica;
        setLocationRelativeTo(null);
        
        popuniCmb();
        if(formEnum.equals(FormEnum.IZMENA)){
            txtRezultat.setText(utakmica.getRezultat());
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            txtDatum.setText(sdf.format(utakmica.getDatum()));
            txtStadion.setText(utakmica.getStadion());
            txtKolo.setText(utakmica.getKolo()+"");
            cmbDomacin.setSelectedItem(utakmica.getDomacin());
            cmbGost.setSelectedItem(utakmica.getGost());
            btnDodaj.setText("izmeni");
        }
    }

    private void popuniCmb(){
        try {

            List<Klub> list = ClientController.getInstance().getAllKlub();
            cmbDomacin.removeAllItems();
            cmbGost.removeAllItems();
            for (Klub klub : list) {
                cmbDomacin.addItem(klub);
                cmbGost.addItem(klub);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRezultat = new javax.swing.JTextField();
        txtDatum = new javax.swing.JFormattedTextField();
        txtStadion = new javax.swing.JTextField();
        txtKolo = new javax.swing.JFormattedTextField();
        cmbDomacin = new javax.swing.JComboBox<>();
        cmbGost = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Rezultat");

        jLabel2.setText("Datum(dd.MM.yyyy HH:mm)");

        jLabel3.setText("Stadion");

        jLabel4.setText("Kolo");

        jLabel5.setText("Domacin");

        jLabel6.setText("Gost");

        txtDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm"))));

        txtKolo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRezultat)
                            .addComponent(txtStadion)
                            .addComponent(txtKolo)
                            .addComponent(cmbDomacin, 0, 220, Short.MAX_VALUE)
                            .addComponent(cmbGost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStadion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDomacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try{
            String rezultat = txtRezultat.getText();
            if(rezultat.isEmpty()){
                throw new Exception("Niste uneli rezultat");
            }
            
            String textDatum = txtDatum.getText();
            if(textDatum.isEmpty()){
                throw new Exception("Niste uneli datum");
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            Date datum = sdf.parse(textDatum);
            if(!datum.before(new Date())){
                throw new Exception("Datum i vreme utakmice mora biti pre trenutnog datuma i vremena");
            }
            
            String stadion = txtStadion.getText();
            if(stadion.isEmpty()){
                throw new Exception("Niste uneli stadion");
            }
            
            String textKolo = txtKolo.getText();
            if(textKolo.isEmpty()){
                throw new Exception("Niste uneli kolo");
            }
            
            int kolo = Integer.parseInt(textKolo);
            if(kolo<1){
                throw new Exception("Kolo mora biti vece od 0");
            }
            
            Klub domacin = (Klub) cmbDomacin.getSelectedItem();
            Klub gost = (Klub) cmbGost.getSelectedItem();
            
            if(domacin.equals(gost)){
                throw new Exception("Domacin i gost moraju biti razlciti klubovi");
            }
            
            utakmica.setRezultat(rezultat);
            utakmica.setDatum(datum);
            utakmica.setStadion(stadion);
            utakmica.setKolo(kolo);
            utakmica.setDomacin(domacin);
            utakmica.setGost(gost);
            
            if(formEnum.equals(FormEnum.IZMENA)){
                ClientController.getInstance().editUtakmica(utakmica);
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili utakmicu");
                this.dispose();
            }else{
                tableModelUtakmica.addUtakmica(utakmica);
                this.dispose();
            }
        }catch(Exception ex){
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnDodajActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox<Object> cmbDomacin;
    private javax.swing.JComboBox<Object> cmbGost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField txtDatum;
    private javax.swing.JFormattedTextField txtKolo;
    private javax.swing.JTextField txtRezultat;
    private javax.swing.JTextField txtStadion;
    // End of variables declaration//GEN-END:variables
}
