/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;


import controller.ClientController;
import domen.Igrac;
import domen.Klub;
import domen.RasporedUtakmica;
import form.klub.NewKlubForm;
import form.klub.SearchKlubForm;
import form.igrac.NewIgracForm;
import form.igrac.SearchIgracForm;
import form.rasporedutakmica.NewRasporedUtakmicaForm;
import form.utakmica.SearchUtakmicaForm;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            lblTrenutnoUlogovani.setText(ClientController.getInstance().getUlogovani().toString());
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        lblTrenutnoUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIgrac = new javax.swing.JMenu();
        menuItemNoviIgrac = new javax.swing.JMenuItem();
        menuItemPretragaIgraca = new javax.swing.JMenuItem();
        menuKlub = new javax.swing.JMenu();
        menuItemNoviKlub = new javax.swing.JMenuItem();
        menuItemPretragaKlubova = new javax.swing.JMenuItem();
        menuRasporedUtakmica = new javax.swing.JMenu();
        menuItemNovRasporedUtakmica = new javax.swing.JMenuItem();
        menuPretragaUtakmica = new javax.swing.JMenu();
        menuItemPretragaUtakmica = new javax.swing.JMenuItem();
        menuPredmet = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        lblTrenutnoUlogovani.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrenutnoUlogovani.setText("jLabel1");

        menuIgrac.setText("Igrac");

        menuItemNoviIgrac.setText("Novi Igrac");
        menuItemNoviIgrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviIgracActionPerformed(evt);
            }
        });
        menuIgrac.add(menuItemNoviIgrac);

        menuItemPretragaIgraca.setText("Pretraga Igraca");
        menuItemPretragaIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaIgracaActionPerformed(evt);
            }
        });
        menuIgrac.add(menuItemPretragaIgraca);

        jMenuBar1.add(menuIgrac);

        menuKlub.setText("Klub");

        menuItemNoviKlub.setText("Novi Klub");
        menuItemNoviKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviKlubActionPerformed(evt);
            }
        });
        menuKlub.add(menuItemNoviKlub);

        menuItemPretragaKlubova.setText("Pretraga klubova");
        menuItemPretragaKlubova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaKlubovaActionPerformed(evt);
            }
        });
        menuKlub.add(menuItemPretragaKlubova);

        jMenuBar1.add(menuKlub);

        menuRasporedUtakmica.setText("Raspored Utakmica");

        menuItemNovRasporedUtakmica.setText("Nov Raspored Utakmica");
        menuItemNovRasporedUtakmica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovRasporedUtakmicaActionPerformed(evt);
            }
        });
        menuRasporedUtakmica.add(menuItemNovRasporedUtakmica);

        jMenuBar1.add(menuRasporedUtakmica);

        menuPretragaUtakmica.setText("Utakmica");

        menuItemPretragaUtakmica.setText("Pretraga utakmica");
        menuItemPretragaUtakmica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaUtakmicaActionPerformed(evt);
            }
        });
        menuPretragaUtakmica.add(menuItemPretragaUtakmica);

        jMenuBar1.add(menuPretragaUtakmica);

        menuPredmet.setText("Predmet");

        jMenuItem2.setText("Novi predmet");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuPredmet.add(jMenuItem2);

        jMenuBar1.add(menuPredmet);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrenutnoUlogovani, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrenutnoUlogovani)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNoviIgracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviIgracActionPerformed
        new NewIgracForm(this, rootPaneCheckingEnabled, new Igrac()).setVisible(true);
    }//GEN-LAST:event_menuItemNoviIgracActionPerformed

    private void menuItemNoviKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviKlubActionPerformed
        new NewKlubForm(this, rootPaneCheckingEnabled, FormEnum.NOVI, new Klub()).setVisible(true);
    }//GEN-LAST:event_menuItemNoviKlubActionPerformed

    private void menuItemPretragaKlubovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaKlubovaActionPerformed
        new SearchKlubForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemPretragaKlubovaActionPerformed

    private void menuItemPretragaIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaIgracaActionPerformed
        new SearchIgracForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemPretragaIgracaActionPerformed

    private void menuItemNovRasporedUtakmicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovRasporedUtakmicaActionPerformed
        new NewRasporedUtakmicaForm(this, rootPaneCheckingEnabled, new RasporedUtakmica()).setVisible(true);
    }//GEN-LAST:event_menuItemNovRasporedUtakmicaActionPerformed

    private void menuItemPretragaUtakmicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaUtakmicaActionPerformed
        new SearchUtakmicaForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuItemPretragaUtakmicaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new PredmetForma().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblTrenutnoUlogovani;
    private javax.swing.JMenu menuIgrac;
    private javax.swing.JMenuItem menuItemNovRasporedUtakmica;
    private javax.swing.JMenuItem menuItemNoviIgrac;
    private javax.swing.JMenuItem menuItemNoviKlub;
    private javax.swing.JMenuItem menuItemPretragaIgraca;
    private javax.swing.JMenuItem menuItemPretragaKlubova;
    private javax.swing.JMenuItem menuItemPretragaUtakmica;
    private javax.swing.JMenu menuKlub;
    private javax.swing.JMenu menuPredmet;
    private javax.swing.JMenu menuPretragaUtakmica;
    private javax.swing.JMenu menuRasporedUtakmica;
    // End of variables declaration//GEN-END:variables
}
