/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.klub;

import controller.ClientController;
import domen.Klub;
import domen.StatistikaKluba;
import form.FormEnum;
import java.net.SocketException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

public class NewKlubForm extends javax.swing.JDialog {

    private Klub klub;
    private FormEnum formEnum;
    private TableModelStatistikaKluba tableModelStatistikaKluba;

    public NewKlubForm(java.awt.Frame parent, boolean modal, FormEnum formEnum, Klub klub) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.klub = klub;
        this.formEnum = formEnum;
        this.tableModelStatistikaKluba = new TableModelStatistikaKluba(new LinkedList<>());
        
        tblStatistikaKluba.setModel(tableModelStatistikaKluba);
        
        if (formEnum.equals(FormEnum.IZMENA)) {
            txtNaziv.setText(klub.getNaziv());
            txtGrad.setText(klub.getGrad());
            tableModelStatistikaKluba.setList(klub.getStatistikaKluba());

            btnSacuvaj.setText("Izmeni");
        }
        
        ispisiOpisStatistike();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatistikaKluba = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnObrisiStatistiku = new javax.swing.JButton();
        btnDodajStatistiku = new javax.swing.JToggleButton();
        txtNaziv = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBrojBodova = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrojDatihGolova = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrojPrimljenihGolova = new javax.swing.JFormattedTextField();
        lblOpis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("Grad");

        tblStatistikaKluba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStatistikaKluba);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnObrisiStatistiku.setText("Obrisi statistiku");
        btnObrisiStatistiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStatistikuActionPerformed(evt);
            }
        });

        btnDodajStatistiku.setText("Dodaj statistiku");
        btnDodajStatistiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStatistikuActionPerformed(evt);
            }
        });

        jLabel3.setText("Broj bodova");

        txtBrojBodova.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setText("Broj datih golova");

        jLabel5.setText("Broj primljenih golova");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(txtGrad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojBodova)
                            .addComponent(txtBrojDatihGolova)
                            .addComponent(txtBrojPrimljenihGolova)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajStatistiku))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOpis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiStatistiku, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisiStatistiku)
                    .addComponent(lblOpis))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojBodova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojDatihGolova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojPrimljenihGolova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajStatistiku)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String naziv = txtNaziv.getText();
            if (naziv.isEmpty()) {
                throw new Exception("Niste uneli naziv kluba");
            }

            String grad = txtGrad.getText();
            if (grad.isEmpty()) {
                throw new Exception("Niste uneli grad kluba");
            }

            List<StatistikaKluba> lista = tableModelStatistikaKluba.getList();
            if (lista.isEmpty()) {
                throw new Exception("Morate uneti barem jednu statistiku kluba");
            }
            
            klub.setNaziv(naziv);
            klub.setGrad(grad);
            klub.setStatistikaKluba(lista);

            ClientController.getInstance().saveKlub(klub);
            if (formEnum.equals(FormEnum.IZMENA)) {
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili klub");
            } else {                
                JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali klub");
            }
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnDodajStatistikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStatistikuActionPerformed
        try {
            String textBrojBodova = txtBrojBodova.getText();
            if(textBrojBodova.isEmpty()){
                throw new Exception("Niste uneli broj bodova");
            }
            
            String textBrojDatihGolova = txtBrojDatihGolova.getText();
            if(textBrojDatihGolova.isEmpty()){
                throw new Exception("Niste uneli broj datih golova");
            }
            
            String textBrojPrimljenihGolova = txtBrojPrimljenihGolova.getText();
            if(textBrojPrimljenihGolova.isEmpty()){
                throw new Exception("Niste uneli broj primljenih golova");
            }
            
            int brojBodova = Integer.parseInt(textBrojBodova);
            int brojDatihGolova = Integer.parseInt(textBrojDatihGolova);
            int brojPrimljenihGolova = Integer.parseInt(textBrojPrimljenihGolova);
            
            if(brojDatihGolova<0){
                throw new Exception("Broj primljenih golova ne moze biti manji od nula");
            }
            if(brojPrimljenihGolova<0){
                throw new Exception("Broj primljenih golova ne moze biti manji od nula");
            }
            
            StatistikaKluba statistikaKluba = new StatistikaKluba(0, klub, brojBodova, brojDatihGolova, brojPrimljenihGolova);
            tableModelStatistikaKluba.addStatistikaKluba(statistikaKluba);
            ispisiOpisStatistike();
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            if (ex instanceof NumberFormatException) {
                JOptionPane.showMessageDialog(this, "Niste ispravno uneli ocenu eksponata. Mogu se uneti samo brojevi");
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDodajStatistikuActionPerformed

    private void btnObrisiStatistikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStatistikuActionPerformed
        int row = tblStatistikaKluba.getSelectedRow();
        if (row > -1) {
            tableModelStatistikaKluba.removeStatistikaKluba(row);
            ispisiOpisStatistike();
        }
    }//GEN-LAST:event_btnObrisiStatistikuActionPerformed

    private void ispisiOpisStatistike(){
        List<StatistikaKluba> list = tableModelStatistikaKluba.getList();
        
        int ukupnoBodova=0;
        int ukupnoDatihGolova = 0;
        int ukupnoPrimljenihGolova = 0;
        
        for(StatistikaKluba sk: list){
            ukupnoBodova+= sk.getBrojBodova();
            ukupnoDatihGolova+= sk.getBrojDatihGolova();
            ukupnoPrimljenihGolova+= sk.getBrojPrimljenihGolova();
        }
        
        lblOpis.setText("Ukupno bodova: "+ ukupnoBodova+"; ukupno datih golova: "+ukupnoDatihGolova+"; ukupno primljenih golova: "+ ukupnoPrimljenihGolova);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JToggleButton btnDodajStatistiku;
    private javax.swing.JButton btnObrisiStatistiku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JTable tblStatistikaKluba;
    private javax.swing.JFormattedTextField txtBrojBodova;
    private javax.swing.JFormattedTextField txtBrojDatihGolova;
    private javax.swing.JFormattedTextField txtBrojPrimljenihGolova;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

}
