/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.klub;

import controller.ClientController;
import domen.Igrac;
import domen.Klub;
import domen.StatistikaKluba;
import form.FormEnum;
import form.igrac.TableModelIgrac;
import java.awt.Frame;
import java.net.SocketException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class SearchKlubForm extends javax.swing.JDialog {

    private TableModelKlub tableModelKlub;
    private TableModelStatistikaKluba tableModelStatistikaKluba;
    private TableModelIgrac tableModelIgrac;

    public SearchKlubForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTableModels();
    }

    private void setTableModels() {
        try {
            List<Klub> list = ClientController.getInstance().getAllKlub();
            tableModelKlub = new TableModelKlub(list);
            tblKlub.setModel(tableModelKlub);
            
            
            tableModelIgrac = new TableModelIgrac(new LinkedList<>());
            tblIgraci.setModel(tableModelIgrac);
            
            tableModelStatistikaKluba = new TableModelStatistikaKluba(new LinkedList<>());
            tblStatistikeKluba.setModel(tableModelStatistikaKluba);
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlub = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatistikeKluba = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtParam = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        lblOpis = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKlub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKlub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKlubMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKlub);

        jLabel1.setText("Statistike");

        tblStatistikeKluba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStatistikeKluba);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Pretraga");

        txtParam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParamKeyReleased(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIgraci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIgraciMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblIgraci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblOpis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeni)
                        .addGap(510, 510, 510))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtParam, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblOpis))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnCancel)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKlubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKlubMouseClicked
        try{
            int row = tblKlub.getSelectedRow();
            if (row > -1) {
                Klub klub = tableModelKlub.getSelected(row);

               tableModelStatistikaKluba.setList(klub.getStatistikaKluba());

               List<Igrac> igraci = ClientController.getInstance().getAllIgracFromKlub(klub);
               tableModelIgrac.setList(igraci);
               ispisiOpisStatistike();
            }
        }catch(Exception ex){
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblKlubMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtParamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamKeyReleased
        try {
            String param = txtParam.getText();
            List<Klub> list;
            if (param.equals("")) {
                list = ClientController.getInstance().getAllKlub();
            } else {
                list = ClientController.getInstance().searchKlub(param);
            }
            tableModelKlub.setList(list);
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtParamKeyReleased

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int row = tblKlub.getSelectedRow();
        if(row>-1){
            Klub klub =tableModelKlub.getSelected(row);
            new NewKlubForm((Frame)this.getParent(), rootPaneCheckingEnabled, FormEnum.IZMENA, klub).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void tblIgraciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIgraciMouseClicked
        
    }//GEN-LAST:event_tblIgraciMouseClicked

    private void ispisiOpisStatistike(){
        List<StatistikaKluba> list = tableModelStatistikaKluba.getList();
        
        int ukupnoBodova=0;
        int ukupnoDatihGolova = 0;
        int ukupnoPrimljenihGolova = 0;
        
        for(StatistikaKluba sk: list){
            ukupnoBodova+= sk.getBrojBodova();
            ukupnoDatihGolova+= sk.getBrojDatihGolova();
            ukupnoPrimljenihGolova+= sk.getBrojPrimljenihGolova();
        }
        
        lblOpis.setText("Ukupno bodova: "+ ukupnoBodova+"; ukupno datih golova: "+ukupnoDatihGolova+"; ukupno primljenih golova: "+ ukupnoPrimljenihGolova);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JTable tblIgraci;
    private javax.swing.JTable tblKlub;
    private javax.swing.JTable tblStatistikeKluba;
    private javax.swing.JTextField txtParam;
    // End of variables declaration//GEN-END:variables
}
